name: music_player
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.4.2
  path_provider: ^1.6.5
  audioplayer: ^0.8.1
  local_notifications: ^0.0.7
  dynamic_theme:
      git:
        url: git://github.com/Norbert515/dynamic_theme.git
  palette_generator: ^0.2.2

flutter_icons:
  android: true
  ios: true
  image_path: "img/placeholder.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - img/placeholder.png

  fonts:
    - family: BalooBhaina
      fonts:
        - asset: fonts/BalooBhaina2-Regular.ttf
